# Generated by Django 4.2.7 on 2023-12-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distributor',
            field=models.CharField(max_length=200),
        ),
    ]
