# Generated by Django 4.2.7 on 2023-12-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('product_id', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
