# Generated by Django 4.2.7 on 2023-12-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='realmane',
            new_name='realname',
        ),
    ]
