# Generated by Django 4.2.7 on 2023-12-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_user_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation',
            new_name='name',
        ),
    ]
