# Generated by Django 4.2.7 on 2023-12-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_reservation_reservation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='reservation_id',
        ),
    ]
