# Generated by Django 4.2.7 on 2023-12-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_rename_name_reservation_reservation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_id',
            new_name='reservation_number',
        ),
    ]
